### PR TITLE
Compatibility with PokeFarmer Hash Server

### PR DESCRIPTION
**Pull request by niicojs**
Change for existing apps should be minimal:
`client.setVersion('5100')`  - Same version user should send to downloadRemoteConfig() or getAstDigest() so we don't introduce a new version format
`clint.activateHashServer('key')`

### CODE REVIEW

**Comment by cyraxx** [comment]
Nice, thanks. I'd like to refactor a few things but I will just take care of that after merging, together with the options hash refactoring.

So now we need to wait for some changes on the starkevin repo first, right?

**Comment by niicojs** [comment]
Yes we need to wait a bit. Or merge to a branch to start working on it while using https://github.com/pogosandbox/node-pogo-signature/tree/hash.

I'm looking right now about retrying is throttle by the hash server, but I think I'll do that in the signature lib.

**Review by ghost — CHANGES_REQUESTED** [review]
Line 152 – using hardcoded host (`http://hashing.pogodev.io/`) even though `this.hashServerHost` exists

**Comment by ghost** [comment]
Also, should we use https instead of http? https://pokehash.buddyauth.com/ provides SSL support.

**Comment by niicojs** [comment]
Fair question... starkevin used hashing.pogodev.io, and I'd rather use the community name instead of the commercial one. but agree no ssl is bad.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
As the [official getting started guide](https://talk.pogodev.org/d/54-getting-started-with-our-api-hashing-service) states, SSL is _coming_ to hashing.pogodev.io, but who knows when...

**Comment by niicojs** [comment]
Working example: https://github.com/pogosandbox/pogonode

**Pull request merged**
