### PR TITLE
Fix egg incubator parsing (potential breaking change, works for me)

### PR DESCRIPTION
**Pull request by niicojs**
Do not merge right now, need some testing.

### CODE REVIEW

**Comment by cyraxx** [comment]
Have you seen cases where the fallback is needed at all?
If the current API is only returning data in a certain way then I'm fine with simply expecting the data to be that way. No need for a fallback if it never runs.

**Comment by niicojs** [comment]
Are you talking about the latest commit or the whole PR?
For the latest commit, the python lib I used some time ago did this so I've added it just in case.
I guess api cannot break so this is to be sure...

**Comment by cyraxx** [comment]
I just meant the last one. If there are currently no API responses that make the fallback necessary then we could get rid of it. But someone :wink: would have to do some testing for that :smiley:

**Comment by jolle** [comment]
I don't think "because Python API does x" is a valid reason anyway (why does Python API do x?).

**Comment by niicojs** [comment]
I'll do some test tonight or tomorrow but there is now way to be sure we are exhaustive

**Comment by cyraxx** [comment]
Thanks :) Yeah if you run a couple tests and never get a response that would make the fallback necessary then that's fine with me. We can always add it back in if we run into issues.

**Comment by niicojs** [comment]
Did not have an issue since. But I obviously did not test with latest api. I don't run map nor bot, just make it for fun in order to improve api so I won't pay access to the hash server.

**Pull request merged**
