### PR TITLE
Include request type in response object

### PR DESCRIPTION
**Pull request by niicojs**
Convenient for easy parsing of response batch.

### CODE REVIEW

**Comment by niicojs** [comment]
For now I added it as an option in constructor, but has to be discussed as you probably want other options for hash server.

**Comment by niicojs** [comment]
an example of use: https://github.com/pogosandbox/pogonode/blob/0380b91a85ec3982e4681a8c800264c95ca0fe1e/helpers/api.js#L241-L263

**Review by ghost — CHANGES_REQUESTED** [review]
Passing client options as an object is a good idea, but it would be better to be unified with other options: enabling/disabling with functions (i.e. setAutomaticLongConversionEnabled). You could put all options (old ones too) to the object _or_ just ditch options object for now and make a function for turning that off/on.

**Review by niicojs — COMMENTED** [review]
done

**Review by ghost — APPROVED** [review]

**Review by ghost — CHANGES_REQUESTED** [review]
Line 23 – invalid jsdoc

**Review by cyraxx — CHANGES_REQUESTED** [review]
I like the idea, I'm just not a fan of the naming. Instead of `pogoBufRequest` I'd suggest something like `_requestType` (unless someone has a better idea).

`setIncludeReqTypeInResponse` is a little long but I can't think of anything shorter that wouldn't be confusing so I guess we'll keep it. Please avoid the `Req` abbrevation in the method name and change it to `Request` though.

**Comment by niicojs** [comment]
I wanted to do _requestType actually, but eslint didn't agree...

**Comment by cyraxx** [comment]
Oh, you're right. I think in this case it's fine to add an exception like so:
```javascript
/* eslint-disable no-underscore-dangle */
responseMessage._requestType = requests[i].type;
/* eslint-enable no-underscore-dangle */
```

We want the underscore here to make sure it will never interfere with any property a response message might contain.

**Review by cyraxx — APPROVED** [review]

**Pull request merged**
