### PR TITLE
add more data to envelop

### PR DESCRIPTION
**Pull request by niicojs**

### CODE REVIEW

**Comment by cyraxx** [comment]
Can you explain a bit why/how you changed the request ID generation? We had some discussion about this a while ago and in the end decided to not increase it per request but go with a completely random value each time instead.

**Comment by niicojs** [comment]
this is the actual generation from the app. at least it was in 0.35 when mitm was easier than now.
the python lib use the same algorithm.

**Comment by niicojs** [comment]
also, this is what the iOS app does, Android is different but all signature is from iOS anyway.

**Comment by cyraxx** [comment]
Very nice, only one tiny thing: Is there a reason why POGOProtos is stored in an instance variable first? Why not get rid of the variable and do this:
`self.signatureBuilder = new pogoSignature.Builder({ protos: POGOProtos });`

**Comment by niicojs** [comment]
Yes, because the app will need access to those protos also. 
For example: https://github.com/nicoschmitt/pogonode/blob/master/signature-helper.js

the issue I have if I don't do that is that protobufjs rely on instance for class, so 'Signature' === 'Signature' works only if I can use the actual protos instance used by node-pogo-signature and pogobuff.

**Comment by cyraxx** [comment]
I've had a look at why you even need to do that and I think the issue is that [in node-pogo-signature's  `buildSignature()` method](https://github.com/SpencerSharkey/node-pogo-signature/blob/master/lib/Builder.js#L90) it encodes the signature proto _first_ and _then_ sets the additional fields that were set via `setFields()`. If this was changed so that the fields are set on the object that goes into the signature proto before encoding it, your app wouldn't need to handle protos at all.

So my suggestion is, do this in node-pogo-signature's `Builder.js`:

```
let signatureData = {
    location_hash1: hash1,
    location_hash2: hash2,
    timestamp: this.time || new Date().getTime(),
    timestamp_since_start: this.time_since_start || (new Date().getTime() - this.initTime),
    unknown25: longjs.fromString("16892874496697272497", true, 10)
};

for(let field in this.fields) {
    signatureData[field] = this.fields[field];
}

let signature = new PROTO_Signature(signatureData);
```

And then your app can simply return objects:

```
infos.device_info = {
    device_id: config.device.id,
    device_brand: "Apple",
    device_model: "iPhone",
    device_model_boot: "iPhone8,2",
    hardware_manufacturer: "Apple",
    hardware_model: "N66AP",
    firmware_brand: "iPhone OS",
    firmware_type: "9.3.5"
};
```

And there's no need to expose the protobuf instance from pogobuf anymore either.

**Pull request merged**
