### PR TITLE
Added IV function

### PR DESCRIPTION
**Pull request by ar1a**

### CODE REVIEW

**Comment by rdzar** [comment]
May be obvious, but I'm not so familiar with the Pokéstats. What does the percentage for a Pokémon mean? :) (`percent`)

**Comment by ar1a** [comment]
I'm not too sure,  I think it's how potentially good it is,  if it's 100
percent then it's the best it can be

**Comment by MRokas** [comment]
poke object passed into function, already has it's IV value.

**Comment by ar1a** [comment]
not the percentage, this is (obviously) a wrapper

**Comment by MRokas** [comment]
multiple it by *100 and you get percentage

**Pull request merged**
