### PR TITLE
Throw an error when server status code is not 2

### PR DESCRIPTION
**Pull request by MakuraYami**
Looks like github removed the end of file newline on its own, can look into that if its a problem.

### CODE REVIEW

**Comment by MakuraYami** [comment]
Wrote this when server was being wonky, didn't notice I forgot about the initial 53 response, will make a new one soon.

**Comment by cyraxx** [comment]
I suspect you saw issue #15 then?

What I had in mind there was whenever you get status code 53, retry the same request for a maximum of, say, five times, and throw an Error if you still get 53.

**Comment by MakuraYami** [comment]
Status code 53 is not an error though? It's just what it gives on successful auth, notifying that you should apply the api_url and auth_ticket and do the request again. If your second request to the new api endpoint fails then you should get a different status code. I wanted to change it so that if status code is 53 and there is no api_url and no auth_ticket it would throw an error, but wasn't sure if you wanted that.

**Comment by cyraxx** [comment]
Oh, yeah, that's what I meant: When getting 53, retry the same request (which will then go to the new endpoint). But have a retry limit in there so you don't run into an endless loop in case the API keeps sending 53 for some reason.

Throwing an error on a 53 without an api_url is a good call!

I'd just leave the auth_ticket out of the equation I think, just store it if we get one, and if we don't then we can use auth_info again for the next request I guess.

**Comment by MakuraYami** [comment]
Since I dunno where else to ask a quick question, is using ES6 in my PR's okay? I see you've used arrow functions sometimes but you did not use classes for example. I'm trying to extend EventEmitter which was really awkward to do before classes were a thing.

**Comment by cyraxx** [comment]
Yep, generally ES6 is fine. I've targeted node 4.0.0 in `package.json` but I'm not too concerned about increasing that to a more recent one if needed.

The reason I didn't use ES6 classes is quite simply because I've never used them before ¯\_(ツ)_/¯ but feel free to refactor into them if you're up for that.

**Pull request closed without merging**
