### PR TITLE
Typescript pogobuf.d.ts typings

### PR DESCRIPTION
**Pull request by Alph44rchitect**
I startet working on Typescript typings #3. @allTypescriptDevelopers feel free to help me! ;)
- [x] Add all pogobuf functions
- [x] Create node-pogo-protos typings (https://github.com/cyraxx/node-pogo-protos/pull/3)
- [x] Import node-pogo-protos typings
- [x] Give functions stronger parameter and returning types

### CODE REVIEW

**Comment by MakuraYami** [comment]
You're doing some great work, appreciate it a lot. Time to start learning typescript.

**Comment by Alph44rchitect** [comment]
Thanks. The autocompletion is it worth. ;)

**Comment by dabnoj** [comment]
how can i update with npm ? like  ----> npm update pogobuff --save?

**Comment by ghost** [comment]
@dabnoj: If you want to get these typescript typings, you should clone @Alph44rchitect's GitHub fork:

**npm**

```
npm install git+https://github.com/Alph44rchitect/pogobuf.git --save
```

**git**

```
git clone https://github.com/Alph44rchitect/pogobuf.git
```

If you want to update your pogobuf version to the current one, you should do `npm update pogobuf`.

Please note that this is a pull request and these typings are not in pogobuf's official release.

**Comment by Alph44rchitect** [comment]
Latest version of `pogobuf.d.ts` depends on the response typings from https://github.com/cyraxx/node-pogo-protos/pull/3 so you have also to clone this when you want to go @joelfi 's way.

Or until everything merged you could just copy `pogobuf.d.ts` and `pogo-protos.d.ts` into your project. Then you need to import the `pogobuf.d.ts` typings via 
`/// <reference path="path/to/pogobuf.d.ts" />`
and update the path inside `pogobuf.d.ts` to the correct path of the `pogo-protos.d.ts`.

If you still have any questions. Feel free to ask. :)

**Comment by cyraxx** [comment]
Shouldn't it be possible to reference the proto definitions with `/// <reference path="node_modules/node-pogo-protos/pogo-protos.d.ts" />`? The node-pogo-protos need to be in there anyway for pogobuf to work.

**Comment by Alph44rchitect** [comment]
When you npm install this package you have to go one direction higher and then deeper because the pogobuf.d.ts is also laying inside node_modules/pogobuf.

**Comment by cyraxx** [comment]
You're absolutely right, I'm an idiot. 😄

**Pull request merged**
